export const STOPWORDS = new Set([
  // Articles
  "the", "a", "an",
  
  // Conjunctions
  "and", "or", "but", "nor", "yet", "so",
  
  // Prepositions
  "in", "on", "at", "to", "for", "of", "with", "from", "by", "about",
  "as", "into", "through", "during", "before", "after", "above", "below",
  "between", "under", "over", "among", "within", "without", "via",
  
  // Pronouns
  "i", "you", "he", "she", "it", "we", "they", "them", "their", "my",
  "your", "his", "her", "its", "our", "who", "which", "what", "that",
  
  // Common verbs
  "is", "are", "was", "were", "be", "been", "being", "have", "has", "had",
  "do", "does", "did", "will", "would", "could", "should", "may", "might",
  "must", "can",
  
  // Other common words
  "this", "that", "these", "those", "all", "each", "every", "some", "any",
  "such", "other", "than", "then", "there", "here", "when", "where", "why",
  "how", "not", "no", "yes", "also", "very", "just", "more", "most", "much",
  "many", "few", "less", "least", "both", "either", "neither"
]);

export const SYNONYMS = {
  // AI/ML
  "ml": "machine learning",
  "ai": "artificial intelligence",
  "dl": "deep learning",
  "cv": "computer vision",
  "nlp": "natural language processing",
  "nn": "neural networks",
  "cnn": "convolutional neural networks",
  "rnn": "recurrent neural networks",
  "gan": "generative adversarial networks",
  "llm": "large language models",
  
  // Programming Languages
  "js": "javascript",
  "ts": "typescript",
  "py": "python",
  "cpp": "c plus plus",
  "cs": "c sharp",
  "rb": "ruby",
  "go": "golang",
  "kt": "kotlin",
  "objc": "objective c",
  "sql": "structured query language",
  "cpp": "cplusplus",
  "c++": "cplusplus",
  "cs": "csharp",
  "c#": "csharp",
  "fs": "fsharp",
  "f#": "fsharp",
  ".net": "dotnet",
  "node": "nodejs",
  "node.js": "nodejs",
  "vue": "vuejs",
  "react": "reactjs",
  "next": "nextjs",
  "objc": "objectivec",
  "objective-c": "objectivec",
  "asp.net": "aspnet",
  "ado.net": "adonet",
  "nuxt.js": "nuxtjs",
  "express.js": "expressjs",
  "nest.js": "nestjs",
  "d3.js": "d3js",
  "three.js": "threejs",
  "p5.js": "p5js",
  "chart.js": "chartjs",
  "socket.io": "socketio",
  "c/c++": "c cplusplus",
  "html5": "html",
  "css3": "css",
  "es6": "javascript",
  "typescript": "typescript",
  "postgresql": "postgresql",
  "mysql": "mysql",
  "mongodb": "mongodb",
  
  // Cloud Platforms
  "aws": "amazon web services",
  "gcp": "google cloud platform",
  "azure": "microsoft azure",
  "ec2": "elastic compute cloud",
  "s3": "simple storage service",
  "rds": "relational database service",
  "ecs": "elastic container service",
  "eks": "elastic kubernetes service",
  "lambda": "aws lambda",
  
  // Databases
  "db": "database",
  "rdbms": "relational database management system",
  "nosql": "non relational database",
  "psql": "postgresql",
  "mysql": "my sql",
  "mssql": "microsoft sql server",
  "mongodb": "mongo database",
  "redis": "remote dictionary server",
  "dynamodb": "dynamo database",
  
  // DevOps & Tools
  "cicd": "continuous integration continuous deployment",
  "ci": "continuous integration",
  "cd": "continuous deployment",
  "k8s": "kubernetes",
  "docker": "containerization",
  "tf": "terraform",
  "iac": "infrastructure as code",
  "git": "version control",
  "jenkins": "automation server",
  "ansible": "configuration management",
  
  // Frontend
  // "html": "hypertext markup language",
  // "css": "cascading style sheets",
  "ui": "user interface",
  "ux": "user experience",
  "spa": "single page application",
  "pwa": "progressive web application",
  "dom": "document object model",
  "jsx": "javascript xml",
  // "sass": "syntactically awesome style sheets",
  "webpack": "module bundler",
  
  // Backend & APIs
  // "api": "application programming interface",
  // "rest": "representational state transfer",
  "restful": "rest api",
  // "graphql": "graph query language",
  // "crud": "create read update delete",
  "orm": "object relational mapping",
  "mvc": "model view controller",
  // "jwt": "json web token",
  "oauth": "open authorization",
  "soap": "simple object access protocol",
  
  // Testing
  "qa": "quality assurance",
  "qc": "quality control",
  "tdd": "test driven development",
  "bdd": "behavior driven development",
  "e2e": "end to end testing",
  "uat": "user acceptance testing",
  
  // Data & Analytics
  "etl": "extract transform load",
  "bi": "business intelligence",
  "dwh": "data warehouse",
  "olap": "online analytical processing",
  "oltp": "online transaction processing",
  "kpi": "key performance indicator",
  "roi": "return on investment",
  
  // Methodologies
  "agile": "agile methodology",
  "scrum": "scrum methodology",
  "kanban": "kanban methodology",
  "lean": "lean methodology",
  "sdlc": "software development life cycle",
  "pmp": "project management professional",
  "prince2": "projects in controlled environments",
  "six sigma": "six sigma methodology",
  "kaizen": "continuous improvement",
  
  // Security
  "infosec": "information security",
  "appsec": "application security",
  "iam": "identity and access management",
  "sso": "single sign on",
  "mfa": "multi factor authentication",
  "2fa": "two factor authentication",
  "vpn": "virtual private network",
  "ssl": "secure sockets layer",
  "tls": "transport layer security",
  "https": "hypertext transfer protocol secure",
  
  // Mobile
  "ios": "iphone operating system",
  "android": "android development",
  "react native": "react native development",
  "flutter": "flutter development",
  "swift": "swift programming",
  "kotlin": "kotlin programming",
  
  // Business & Finance
  "cfo": "chief financial officer",
  "ceo": "chief executive officer",
  "coo": "chief operating officer",
  "cto": "chief technology officer",
  "cmo": "chief marketing officer",
  "cpa": "certified public accountant",
  "cfa": "chartered financial analyst",
  "mba": "master of business administration",
  "p&l": "profit and loss",
  "pl": "profit and loss",
  "ebitda": "earnings before interest taxes depreciation amortization",
  "ebit": "earnings before interest and taxes",
  "opex": "operating expenses",
  "capex": "capital expenditures",
  "yoy": "year over year",
  "qoq": "quarter over quarter",
  "fy": "fiscal year",
  "q1": "first quarter",
  "q2": "second quarter",
  "q3": "third quarter",
  "q4": "fourth quarter",
  "gaap": "generally accepted accounting principles",
  "ifrs": "international financial reporting standards",
  "sox": "sarbanes oxley act",
  "aml": "anti money laundering",
  "kyc": "know your customer",
  "aum": "assets under management",
  "nav": "net asset value",
  "ipo": "initial public offering",
  "m&a": "mergers and acquisitions",
  "pe": "private equity",
  "vc": "venture capital",
  
  // Marketing & Sales
  "seo": "search engine optimization",
  "sem": "search engine marketing",
  "ppc": "pay per click",
  "cpc": "cost per click",
  "cpm": "cost per thousand impressions",
  "ctr": "click through rate",
  "cro": "conversion rate optimization",
  "cac": "customer acquisition cost",
  "ltv": "lifetime value",
  "clv": "customer lifetime value",
  "mrr": "monthly recurring revenue",
  "arr": "annual recurring revenue",
  "smm": "social media marketing",
  "pr": "public relations",
  "b2b": "business to business",
  "b2c": "business to consumer",
  "b2g": "business to government",
  "gtm": "go to market",
  "usp": "unique selling proposition",
  "abm": "account based marketing",
  "drip campaign": "automated email campaign",
  
  // Human Resources
  "hr": "human resources",
  "hris": "human resources information system",
  "ats": "applicant tracking system",
  "onboarding": "employee onboarding",
  "offboarding": "employee offboarding",
  "pto": "paid time off",
  "fmla": "family and medical leave act",
  "ada": "americans with disabilities act",
  "eeoc": "equal employment opportunity commission",
  "osha": "occupational safety and health administration",
  "talent acquisition": "recruiting",
  "l&d": "learning and development",
  "od": "organizational development",
  "comp": "compensation",
  "total rewards": "compensation and benefits",
  "hc": "headcount",
  "fte": "full time equivalent",
  
  // Healthcare
  "rn": "registered nurse",
  "lpn": "licensed practical nurse",
  "md": "medical doctor",
  "do": "doctor of osteopathic medicine",
  "pa": "physician assistant",
  "np": "nurse practitioner",
  "cna": "certified nursing assistant",
  "emt": "emergency medical technician",
  "paramedic": "emergency medical services",
  "cpr": "cardiopulmonary resuscitation",
  "bls": "basic life support",
  "acls": "advanced cardiac life support",
  "pals": "pediatric advanced life support",
  "hipaa": "health insurance portability and accountability act",
  "phi": "protected health information",
  "ehr": "electronic health record",
  "emr": "electronic medical record",
  "epic": "epic systems",
  "cerner": "cerner systems",
  "icd": "international classification of diseases",
  "cpt": "current procedural terminology",
  "dnr": "do not resuscitate",
  "or": "operating room",
  "er": "emergency room",
  "ed": "emergency department",
  "icu": "intensive care unit",
  "nicu": "neonatal intensive care unit",
  "pacu": "post anesthesia care unit",
  
  // Legal
  "jd": "juris doctor",
  "llm": "master of laws",
  "esq": "esquire",
  "paralegal": "legal assistant",
  "ip": "intellectual property",
  "trademark": "registered trademark",
  "copyright": "copyright protection",
  "nda": "non disclosure agreement",
  "mou": "memorandum of understanding",
  "loi": "letter of intent",
  "sla": "service level agreement",
  "msa": "master service agreement",
  "gdpr": "general data protection regulation",
  "ccpa": "california consumer privacy act",
  "ferpa": "family educational rights and privacy act",
  "compliance": "regulatory compliance",
  "litigation": "legal proceedings",
  "arbitration": "dispute resolution",
  "mediation": "alternative dispute resolution",
  
  // Education
  "phd": "doctor of philosophy",
  "edd": "doctor of education",
  "ma": "master of arts",
  "ms": "master of science",
  "mfa": "master of fine arts",
  "ba": "bachelor of arts",
  "bs": "bachelor of science",
  "bfa": "bachelor of fine arts",
  "aa": "associate of arts",
  "as": "associate of science",
  "gpa": "grade point average",
  "sat": "scholastic assessment test",
  "act": "american college testing",
  "gre": "graduate record examination",
  "gmat": "graduate management admission test",
  "lsat": "law school admission test",
  "mcat": "medical college admission test",
  "toefl": "test of english as a foreign language",
  "ielts": "international english language testing system",
  "stem": "science technology engineering mathematics",
  "iep": "individualized education program",
  "504": "section 504 plan",
  "esl": "english as a second language",
  "ell": "english language learner",
  
  // Manufacturing & Supply Chain
  "oee": "overall equipment effectiveness",
  "tpm": "total productive maintenance",
  "jit": "just in time",
  "lean manufacturing": "lean production",
  "5s": "sort set in order shine standardize sustain",
  "sop": "standard operating procedure",
  "iso": "international organization for standardization",
  "gmp": "good manufacturing practice",
  "fda": "food and drug administration",
  "haccp": "hazard analysis critical control points",
  "capa": "corrective and preventive action",
  "bom": "bill of materials",
  "mrp": "material requirements planning",
  "erp": "enterprise resource planning",
  "wms": "warehouse management system",
  "tms": "transportation management system",
  "scm": "supply chain management",
  "sku": "stock keeping unit",
  "fifo": "first in first out",
  "lifo": "last in first out",
  "lead time": "procurement lead time",
  "otd": "on time delivery",
  
  // Real Estate
  "mls": "multiple listing service",
  "hoa": "homeowners association",
  "roi": "return on investment",
  "cap rate": "capitalization rate",
  "noi": "net operating income",
  "dscr": "debt service coverage ratio",
  "ltv": "loan to value",
  "arv": "after repair value",
  "comps": "comparable properties",
  "fsbo": "for sale by owner",
  "reo": "real estate owned",
  
  // General Business
  "kpi": "key performance indicator",
  "okr": "objectives and key results",
  "swot": "strengths weaknesses opportunities threats",
  "raci": "responsible accountable consulted informed",
  "smart": "specific measurable achievable relevant time bound",
  "sow": "statement of work",
  "rfp": "request for proposal",
  "rfq": "request for quote",
  "rfi": "request for information",
  "poc": "proof of concept",
  "mvp": "minimum viable product",
  "tbd": "to be determined",
  "tbc": "to be confirmed",
  "asap": "as soon as possible",
  "eod": "end of day",
  "eow": "end of week",
  "eom": "end of month",
  "eoq": "end of quarter",
  "eoy": "end of year",
  "fte": "full time employee",
  "pt": "part time",
  "wfh": "work from home",
  "remote": "remote work",
  "hybrid": "hybrid work"
};

export const KNOWN_PHRASES = new Set([
  // Technical Skills - Programming
  "machine learning",
  "deep learning",
  "artificial intelligence",
  "natural language processing",
  "computer vision",
  "neural networks",
  "data science",
  "data analysis",
  "data engineering",
  "software engineering",
  "software development",
  "full stack development",
  "front end development",
  "back end development",
  "mobile development",
  "web development",
  "api development",
  "database management",
  "version control",
  "agile development",
  "test driven development",
  "continuous integration",
  "continuous deployment",
  "cplusplus",
  "csharp",
  "fsharp",
  "dotnet",
  "nodejs",
  "vuejs",
  "reactjs",
  "nextjs",
  "expressjs",
  "objectivec",
  
  // Cloud & Infrastructure
  "cloud computing",
  "cloud architecture",
  "aws solutions",
  "azure services",
  "google cloud platform",
  "docker containers",
  "kubernetes orchestration",
  "microservices architecture",
  "serverless computing",
  "infrastructure as code",
  "devops practices",
  "ci cd pipeline",
  
  // Data & Analytics
  "big data",
  "data visualization",
  "business intelligence",
  "statistical analysis",
  "predictive modeling",
  "data mining",
  "etl processes",
  "data warehousing",
  "sql queries",
  "nosql databases",
  "data modeling",
  "ab testing",
  
  // Management & Business
  "project management",
  "product management",
  "team leadership",
  "agile methodologies",
  "scrum master",
  "stakeholder management",
  "business analysis",
  "requirements gathering",
  "risk management",
  "change management",
  "strategic planning",
  "cross functional teams",
  "process improvement",
  "budget management",
  
  // Security & Compliance
  "information security",
  "cybersecurity",
  "network security",
  "data privacy",
  "risk assessment",
  "compliance management",
  "security protocols",
  "penetration testing",
  "vulnerability assessment",
  
  // Soft Skills (important for resumes)
  "problem solving",
  "critical thinking",
  "analytical skills",
  "communication skills",
  "time management",
  "attention to detail",
  "customer service",
  "technical writing",
  "public speaking",
  "conflict resolution",
  
  // Industry-specific
  "user experience",
  "user interface",
  "responsive design",
  "quality assurance",
  "system design",
  "technical support",
  "sales engineering",
  "digital marketing",
  "content management",
  "social media"
]);

export const NO_SINGULARIZE = new Set([
  // Tech & Cloud Services
  "aws",
  "gcp",
  "ecs",
  "eks",
  "rds",
  "kubernetes",
  "jenkins",
  "postgres",
  "redis",
  "analytics",
  "statistics",
  "graphics",
  "dynamics",
  "logistics",
  
  // Web & Design
  "css",
  "sass",
  "less",
  "canvas",
  "photoshop",
  "illustrator",
  
  // Analysis & Research
  "analysis",
  "thesis",
  "basis",
  "crisis",
  "diagnosis",
  "prognosis",
  "synopsis",
  "hypothesis",
  "parenthesis",
  "emphasis",
  
  // Series & Collections
  "series",
  "species",
  "means",
  "news",
  
  // Business & Finance
  "sales",
  "gross",
  "business",
  "economics",
  "ethics",
  "operations",
  "headquarters",
  "proceeds",
  "earnings",
  "savings",
  "assets",
  "goods",
  "liabilities",
  "securities",
  "futures",
  "commons",
  "arrears",
  
  // Healthcare & Medical
  "diabetes",
  "measles",
  "mumps",
  "rabies",
  "herpes",
  "shingles",
  "aids",
  "sars",
  "wellness",
  "fitness",
  "genetics",
  "orthodontics",
  "pediatrics",
  "obstetrics",
  "geriatrics",
  "diagnostics",
  
  // Science & Mathematics
  "mathematics",
  "physics",
  "electronics",
  "robotics",
  "optics",
  "acoustics",
  "thermodynamics",
  "mechanics",
  "bioinformatics",
  "genomics",
  "proteomics",
  
  // Education & Academia
  "humanities",
  "linguistics",
  "phonetics",
  "semantics",
  "civics",
  "athletics",
  "aerobics",
  "gymnastics",
  
  // General Terms
  "scissors",
  "pants",
  "glasses",
  "tweezers",
  "pliers",
  "tongs",
  "trousers",
  "binoculars",
  "goggles",
  "jeans",
  "shorts",
  "thanks",
  "congratulations",
  "regards",
  "credentials",
  "premises",
  "outskirts",
  "suds",
  "dregs",
  "grounds",
  "odds",
  "remains",
  "riches",
  "stairs",
  "surroundings",
  "tropics",
  "utilities",
  "victuals",
  "works",
  "continous",
  "across",
  
  // Proper Nouns & Brand Names
  "reuters",
  "forbes",
  "times",
  "ialis", //ialis inialis
  "ialis",
  
  // Compound Words
  "services",
  "resources",
  "relations",
  "communications",
  "systems",
  "solutions",
  "technologies",
  
  // Games & Entertainment
  "darts",
  "checkers",
  "dominoes",
  "billiards",
  "cards",
  
  // Location/Geography
  "netherlands",
  "philippines",
  "alps",
  "andes",
  "himalayas",
  "bahamas",
  "maldives",
  
  // Mass Nouns (uncountable)
  "progress",
  "access",
  "success",
  "stress",
  "process",
  "congress",
  "recess",
  
  // Already Plural Forms
  "clothes",
  "police",
  "people",
  "cattle",
  "poultry",
  "vermin",
  "clergy",
  
  // Industry Specific
  "customs", // customs clearance
  "damages", // legal damages
  "communications", // field of study
  "contents", // table of contents
  "archives",
  "barracks",
  "chassis",
  "corps",
  "crossroads",
  "gallows",
  "innings",
  "species",
  "whereabouts",

  //Stopwords
  "this",
  "his",
  "its",
  "yes",
  "does",
  "has",

  //Synonym
  "rdbms",
]);

// Complete plural to singular mapping
export const PLURAL_TO_SINGULAR = new Map([
  // -ves to -f/-fe conversions
  ["lives", "life"],
  ["wives", "wife"],
  ["knives", "knife"],
  ["leaves", "leaf"],
  ["shelves", "shelf"],
  ["wolves", "wolf"],
  ["halves", "half"],
  ["calves", "calf"],
  ["thieves", "thief"],
  ["loaves", "loaf"],
  ["selves", "self"],
  
  // -xes endings
  ["boxes", "box"],
  ["foxes", "fox"],
  ["indexes", "index"],
  ["appendixes", "appendix"],
  ["complexes", "complex"],
  ["faxes", "fax"],
  ["taxes", "tax"],
  ["waxes", "wax"],
  ["axes", "axis"], // or "axe" depending on context
  ["fixes", "fix"],
  ["mixes", "mix"],
  ["prefixes", "prefix"],
  ["suffixes", "suffix"],
  
  // -ches endings
  ["churches", "church"],
  ["branches", "branch"],
  ["benches", "bench"],
  ["watches", "watch"],
  ["matches", "match"],
  ["batches", "batch"],
  ["patches", "patch"],
  ["catches", "catch"],
  ["coaches", "coach"],
  ["approaches", "approach"],
  ["beaches", "beach"],
  ["peaches", "peach"],
  ["porches", "porch"],
  ["searches", "search"],
  ["researches", "research"],
  ["arches", "arch"],
  ["lunches", "lunch"],
  ["punches", "punch"],
  ["ranches", "ranch"],
  ["speeches", "speech"],
  ["ditches", "ditch"],
  ["witches", "witch"],
  ["switches", "switch"],
  ["sketches", "sketch"],
  ["stretches", "stretch"],
  
  // -shes endings
  ["dishes", "dish"],
  ["wishes", "wish"],
  ["bushes", "bush"],
  ["brushes", "brush"],
  ["crashes", "crash"],
  ["flashes", "flash"],
  ["ashes", "ash"],
  ["clashes", "clash"],
  ["dashes", "dash"],
  ["hashes", "hash"],
  ["lashes", "lash"],
  ["meshes", "mesh"],
  ["pushes", "push"],
  ["rushes", "rush"],
  ["smashes", "smash"],
  ["splashes", "splash"],
  ["thrashes", "thrash"],
  ["washes", "wash"],
  
  // -sses endings
  ["classes", "class"],
  ["masses", "mass"],
  ["passes", "pass"],
  ["glasses", "glass"],
  ["processes", "process"],
  ["addresses", "address"],
  ["stresses", "stress"],
  ["businesses", "business"],
  ["crosses", "cross"],
  ["bosses", "boss"],
  ["losses", "loss"],
  ["mosses", "moss"],
  ["dresses", "dress"],
  ["presses", "press"],
  ["guesses", "guess"],
  ["messes", "mess"],
  ["witnesses", "witness"],
  ["nesses", "ness"],
  ["esses", "ess"],
  
  // Technology & Devices
  ["devices", "device"],
  ["databases", "database"],
  ["interfaces", "interface"],
  ["caches", "cache"],
  ["resources", "resource"],
  ["services", "service"],
  ["practices", "practice"],
  ["offices", "office"],
  ["notices", "notice"],
  ["licenses", "license"],
  ["franchises", "franchise"],
  ["exercises", "exercise"],
  ["choices", "choice"],
  ["voices", "voice"],
  ["invoices", "invoice"],
  ["slices", "slice"],
  ["prices", "price"],
  ["spaces", "space"],
  ["places", "place"],
  ["traces", "trace"],
  ["faces", "face"],
  ["races", "race"],
  ["bases", "base"],
  ["cases", "case"],
  ["phases", "phase"],
  ["vases", "vase"],
  
  // Languages & Communication
  ["languages", "language"],
  ["messages", "message"],
  ["phrases", "phrase"],
  ["courses", "course"],
  ["clauses", "clause"],
  ["responses", "response"],
  ["purposes", "purpose"],
  ["promises", "promise"],
  ["premises", "premise"],
  ["licenses", "license"],
  ["enses", "ense"],
  
  // Business & Management
  ["enterprises", "enterprise"],
  ["purchases", "purchase"],
  ["expenses", "expense"],
  ["releases", "release"],
  ["increases", "increase"],
  ["decreases", "decrease"],
  
  // Technical Terms
  ["uses", "use"],
  ["abuses", "abuse"],
  ["causes", "cause"],
  ["excuses", "excuse"],
  ["refuses", "refuse"],
  ["accuses", "accuse"],
  ["confuses", "confuse"],
  ["diffuses", "diffuse"],
  ["fuses", "fuse"],
  ["infuses", "infuse"],
  ["peruses", "peruse"],
  ["reuses", "reuse"],
  
  // Common -ies to -y conversions (can be done by rule, but listed for completeness)
  ["libraries", "library"],
  ["stories", "story"],
  ["countries", "country"],
  ["companies", "company"],
  ["cities", "city"],
  ["parties", "party"],
  ["families", "family"],
  ["queries", "query"],
  ["categories", "category"],
  ["batteries", "battery"],
  ["calories", "calory"],
  ["ceremonies", "ceremony"],
  ["dictionaries", "dictionary"],
  ["directories", "directory"],
  ["factories", "factory"],
  ["galleries", "gallery"],
  ["histories", "history"],
  ["injuries", "injury"],
  ["industries", "industry"],
  ["mysteries", "mystery"],
  ["nurseries", "nursery"],
  ["policies", "policy"],
  ["properties", "property"],
  ["strategies", "strategy"],
  ["technologies", "technology"],
  ["theories", "theory"],
  ["territories", "territory"],
  ["uries", "ury"],
  ["victories", "victory"],
  
  // Irregular plurals
  ["people", "person"],
  ["children", "child"],
  ["men", "man"],
  ["women", "woman"],
  ["teeth", "tooth"],
  ["feet", "foot"],
  ["mice", "mouse"],
  ["geese", "goose"],
  ["oxen", "ox"],
  ["criteria", "criterion"],
  ["phenomena", "phenomenon"],
  ["data", "datum"],
  ["curricula", "curriculum"],
  ["bacteria", "bacterium"],
  ["radii", "radius"],
  ["foci", "focus"],
  ["cacti", "cactus"],
  ["fungi", "fungus"],
  ["syllabi", "syllabus"],
  ["alumni", "alumnus"],
  ["indices", "index"],
  ["matrices", "matrix"],
  ["vertices", "vertex"],
  ["appendices", "appendix"]
]);

// Skill categories for weighting
export const SKILL_CATEGORIES = {
  technical: new Set([
    "machine learning",
    "deep learning",
    "artificial intelligence",
    "natural language processing",
    "computer vision",
    "neural networks",
    "data science",
    "software engineering",
    "cloud computing",
    "database management",
    "api development",
    "microservices",
    "devops",
    "kubernetes",
    "docker",
    "python",
    "javascript",
    "typescript",
    "java",
    "react",
    "vue",
    "node",
    "sql",
    "nosql",
    "aws",
    "azure",
    "gcp",
    "cybersecurity",
    "blockchain",
    "data analysis",
    "statistical analysis",
    "algorithm design",
    "system design",
    "backend development",
    "frontend development",
    "full stack development"
  ]),
  
  tools: new Set([
    "git",
    "jira",
    "confluence",
    "slack",
    "figma",
    "sketch",
    "photoshop",
    "excel",
    "powerpoint",
    "tableau",
    "power bi",
    "jenkins",
    "gitlab",
    "github",
    "bitbucket",
    "postman",
    "visual studio",
    "intellij",
    "eclipse",
    "mongodb",
    "postgresql",
    "mysql",
    "redis",
    "elasticsearch",
    "grafana",
    "prometheus",
    "terraform",
    "ansible",
    "salesforce",
    "hubspot",
    "google analytics",
    "adobe analytics"
  ]),
  
  soft: new Set([
    "leadership",
    "communication",
    "teamwork",
    "problem solving",
    "critical thinking",
    "time management",
    "project management",
    "agile",
    "scrum",
    "collaboration",
    "presentation",
    "mentoring",
    "negotiation",
    "adaptability",
    "creativity",
    "attention to detail",
    "analytical skills",
    "organizational skills",
    "customer service",
    "conflict resolution",
    "decision making",
    "stakeholder management"
  ])
};
